name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/repo:latest

      - name: Run tests
        run: |
          docker-compose up -d
          sleep 10
          curl -f http://localhost/api/health || exit 1
          docker-compose down

      - name: Lint configuration files
        run: |
          docker-compose config

      - name: Validate Docker images
        run: |
          docker images

      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          # Add deployment commands here
          # e.g., ssh user@server "docker-compose pull && docker-compose up -d"