name: CI/CD Pipeline - Phase 2

on:
  push:
    branches:
      - main
    paths:
      - 'Phase-2-Intermediate/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: phase2/web:latest
          file: ./Dockerfile

      - name: Lint docker-compose.yml
        run: |
          docker-compose config

      - name: Start services
        run: |
          docker-compose up -d
          sleep 10

      - name: Test container availability
        run: |
          curl -f http://localhost || exit 1
          curl -f http://localhost/api/health || exit 1

      - name: Stop services
        run: |
          docker-compose down
