name: CI/CD Pipeline - Phase 2

on:
  push:
    branches:
      - main
    paths:
      - 'Phase-2-Intermediate/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint docker-compose.yml and cd
        run: |
          sudo apt-get install -y docker-compose
          cd Phase-2-Intermediate
          docker-compose -f docker-compose.yml config

      - name: Build Docker image web
        uses: docker/build-push-action@v6
        with:
          context: ./Phase-2-Intermediate/web
          push: false
          tags: phase-2-intermediate_web:latest
          file: ./Phase-2-Intermediate/web/Dockerfile

      - name: Build Docker image backend
        uses: docker/build-push-action@v6
        with:
          context: ./Phase-2-Intermediate/backend
          push: false
          tags: phase-2-intermediate_backend:latest
          file: ./Phase-2-Intermediate/backend/Dockerfile

      - name: Start services
        run: |
          cd Phase-2-Intermediate
          docker-compose up -d
          sleep 10

      - name: Test container availability
        run: |
          curl -f http://localhost || exit 1
          curl -f http://localhost/api/health || exit 1

      - name: Stop services
        run: |
          docker-compose down
