name: CI/CD Pipeline - Phase 2

on:
  push:
    branches:
      - main
    paths:
      - 'Phase-2-Intermediate/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Lint docker-compose.yml and cd
        run: |
          cd Phase-2-Intermediate
          docker-compose -f docker-compose.yml config

      - name: Build Docker image web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: false
          tags: phase-2-intermediate_web:latest
          file: Dockerfile

      - name: Build Docker image backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: false
          tags: phase-2-intermediate_backend:latest
          file: Dockerfile

      - name: Start services
        run: |
          docker-compose up -d
          sleep 10

      - name: Test container availability
        run: |
          curl -f http://localhost || exit 1
          curl -f http://localhost/api/health || exit 1

      - name: Stop services
        run: |
          docker-compose down
