name: CI/CD Pipeline - Phase 3
on:
  push:
    branches:
      - main
    paths:
      - 'Phase-3-Expert/**'

env:
  VAR_GH_REPO: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Convert repo to lowercase
        id: convertrepo2lowercase
        run: INPUT=${{ env.VAR_GH_REPO }}; echo "VAR_GH_REPO_LC=${INPUT,,}">>${GITHUB_OUTPUT}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint docker-compose.yml and cd
        run: |
          sudo apt-get install -y docker-compose
          cd Phase-3-Expert
          docker-compose -f docker-compose.yml config

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image web
        uses: docker/build-push-action@v6
        with:
          context: ./Phase-3-Expert/web
          push: true
          tags: ghcr.io/${{steps.convertrepo2lowercase.outputs.VAR_GH_REPO_LC}}/phase-3-expert_web:latest
          file: ./Phase-3-Expert/web/Dockerfile

      - name: Build Docker image backend
        uses: docker/build-push-action@v6
        with:
          context: ./Phase-3-Expert/backend
          push: true
          tags: ghcr.io/${{steps.convertrepo2lowercase.outputs.VAR_GH_REPO_LC}}/phase-3-expert_backend:latest
          file: ./Phase-3-Expert/backend/Dockerfile

      - name: Start services
        run: |
          cd Phase-3-Expert
          docker-compose up -d
          sleep 10

      - name: Test container availability
        run: |
          curl -f http://localhost || exit 1
          curl -f http://localhost/api/health || exit 1

      - name: Stop services
        run: |
          cd Phase-3-Expert
          docker-compose down

#  deploy-to-production:
#    # Only run this deploy job after the build-and-test job completes successfully.
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH to remote server and deploy